#cloud-config
users:
  - name: yc-user
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCstqf1FZKh/8Sg2sIgDgl68WpADeORSuqol0rshDPF6h7akOhdjMPQAyOZ9m9uJk9lsoCDmvJdlYG10fkxNLDV8XGThAtf02XmFf133MLIC0hhGq1AoHpma8TSK7U2uDwgOxCu53ZA22roQaaho9uzMh0z2o+YThLOrUIt9jfxdAi2v2mP+6MGPZ7amKKxe3msCJUxbhgBzN4c7039e83g8BUbtnO48NPF0H+ZTYxN+stXZA6ylGYnZ9rcPvqydizq5HTndb4RqK+ylMxkwbQrY0RgDQYCGazJv01kXtVRm0VP3xfd1EIJvoBu75AoIYogBAV5WouumtZniKdnJ7AnhD/MX1ESiOC6gutXgWmNby8DgkNywKXsG1UGYHfn4JEvHrmUhkJurmz5CcsHRTWGGBVsh4fCJHAvGavZSDZATsZUNQ/SfUlxRgDVu/kVrmA6xJVcrSAQTW4tVtk7nGq4gsBYOC7l2XJcG5z94OVd5diqXLjUX3S2VdxxCN8a5D8= appuser

package_update: true

packages:
  - git

runcmd:
  - git clone -b cloud-testapp https://github.com/Otus-DevOps-2022-11/timur8298_infra.git
  - /timur8298_infra/install_ruby.sh
  - /timur8298_infra/install_mongodb.sh
  - /timur8298_infra/deploy.sh
