name: Ansible Lint

on: [push, pull_request]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@main
      with:
        path: "ansible/playbooks/"
